//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMInsurance.Services.DMZ.PolicyStatusService.InternalAuthService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InternalAuthService.IAuthService")]
    public interface IAuthService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/CheckPassword", ReplyAction="http://tempuri.org/IAuthService/CheckPasswordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Entities.Core.Faults.DataObjectNotFoundFault), Action="http://tempuri.org/IAuthService/CheckPasswordDataObjectNotFoundFaultFault", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        bool CheckPassword(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthService/CheckPassword", ReplyAction="http://tempuri.org/IAuthService/CheckPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckPasswordAsync(string user, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthServiceChannel : OMInsurance.Services.DMZ.PolicyStatusService.InternalAuthService.IAuthService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceClient : System.ServiceModel.ClientBase<OMInsurance.Services.DMZ.PolicyStatusService.InternalAuthService.IAuthService>, OMInsurance.Services.DMZ.PolicyStatusService.InternalAuthService.IAuthService {
        
        public AuthServiceClient() {
        }
        
        public AuthServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckPassword(string user, string password) {
            return base.Channel.CheckPassword(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPasswordAsync(string user, string password) {
            return base.Channel.CheckPasswordAsync(user, password);
        }
    }
}
