//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMInsurance.Services.Tests.DMZPolicyStatusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyInfo", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClientVisitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryCenter DeliveryCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryPoint DeliveryPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StatusDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClientVisitDate {
            get {
                return this.ClientVisitDateField;
            }
            set {
                if ((this.ClientVisitDateField.Equals(value) != true)) {
                    this.ClientVisitDateField = value;
                    this.RaisePropertyChanged("ClientVisitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryCenter DeliveryCenter {
            get {
                return this.DeliveryCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryCenterField, value) != true)) {
                    this.DeliveryCenterField = value;
                    this.RaisePropertyChanged("DeliveryCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryPoint DeliveryPoint {
            get {
                return this.DeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointField, value) != true)) {
                    this.DeliveryPointField = value;
                    this.RaisePropertyChanged("DeliveryPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryCenter", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryCenter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryPoint", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class DeliveryPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyStatus", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class PolicyStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault))]
    public partial class ServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerStackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServerStackTrace {
            get {
                return this.ServerStackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerStackTraceField, value) != true)) {
                    this.ServerStackTraceField = value;
                    this.RaisePropertyChanged("ServerStackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
        "")]
    [System.SerializableAttribute()]
    public partial class DataObjectNotFoundFault : OMInsurance.Services.Tests.DMZPolicyStatusService.ServiceFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AttachmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlankNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CitizenshipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ClientVisitDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryCenter DeliveryCenterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryPoint DeliveryPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LPUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomernikStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicySeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyStatus PolicyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StatusDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemporaryPolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnifiedPolicyNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationMethod {
            get {
                return this.ApplicationMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationMethodField, value) != true)) {
                    this.ApplicationMethodField = value;
                    this.RaisePropertyChanged("ApplicationMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AttachmentDate {
            get {
                return this.AttachmentDateField;
            }
            set {
                if ((this.AttachmentDateField.Equals(value) != true)) {
                    this.AttachmentDateField = value;
                    this.RaisePropertyChanged("AttachmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentMethod {
            get {
                return this.AttachmentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentMethodField, value) != true)) {
                    this.AttachmentMethodField = value;
                    this.RaisePropertyChanged("AttachmentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlankNumber {
            get {
                return this.BlankNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BlankNumberField, value) != true)) {
                    this.BlankNumberField = value;
                    this.RaisePropertyChanged("BlankNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Citizenship {
            get {
                return this.CitizenshipField;
            }
            set {
                if ((object.ReferenceEquals(this.CitizenshipField, value) != true)) {
                    this.CitizenshipField = value;
                    this.RaisePropertyChanged("Citizenship");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ClientVisitDate {
            get {
                return this.ClientVisitDateField;
            }
            set {
                if ((this.ClientVisitDateField.Equals(value) != true)) {
                    this.ClientVisitDateField = value;
                    this.RaisePropertyChanged("ClientVisitDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryCenter DeliveryCenter {
            get {
                return this.DeliveryCenterField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryCenterField, value) != true)) {
                    this.DeliveryCenterField = value;
                    this.RaisePropertyChanged("DeliveryCenter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.DeliveryPoint DeliveryPoint {
            get {
                return this.DeliveryPointField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryPointField, value) != true)) {
                    this.DeliveryPointField = value;
                    this.RaisePropertyChanged("DeliveryPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LPU {
            get {
                return this.LPUField;
            }
            set {
                if ((object.ReferenceEquals(this.LPUField, value) != true)) {
                    this.LPUField = value;
                    this.RaisePropertyChanged("LPU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomernikStatus {
            get {
                return this.NomernikStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.NomernikStatusField, value) != true)) {
                    this.NomernikStatusField = value;
                    this.RaisePropertyChanged("NomernikStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySeries {
            get {
                return this.PolicySeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicySeriesField, value) != true)) {
                    this.PolicySeriesField = value;
                    this.RaisePropertyChanged("PolicySeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyStatus PolicyStatus {
            get {
                return this.PolicyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyStatusField, value) != true)) {
                    this.PolicyStatusField = value;
                    this.RaisePropertyChanged("PolicyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secondname {
            get {
                return this.SecondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondnameField, value) != true)) {
                    this.SecondnameField = value;
                    this.RaisePropertyChanged("Secondname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemporaryPolicyNumber {
            get {
                return this.TemporaryPolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TemporaryPolicyNumberField, value) != true)) {
                    this.TemporaryPolicyNumberField = value;
                    this.RaisePropertyChanged("TemporaryPolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnifiedPolicyNumber {
            get {
                return this.UnifiedPolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UnifiedPolicyNumberField, value) != true)) {
                    this.UnifiedPolicyNumberField = value;
                    this.RaisePropertyChanged("UnifiedPolicyNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secondname {
            get {
                return this.SecondnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondnameField, value) != true)) {
                    this.SecondnameField = value;
                    this.RaisePropertyChanged("Secondname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities")]
    [System.SerializableAttribute()]
    public partial class Region : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DMZPolicyStatusService.IPolicyStatusService")]
    public interface IPolicyStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByUnifiedPolicyNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByUnifiedPolicyNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault), Action="http://tempuri.org/IPolicyStatusService/GetStatusByUnifiedPolicyNumberDataObjectN" +
            "otFoundFaultFault", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByUnifiedPolicyNumber(int regionId, string unifiedPolicyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByUnifiedPolicyNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByUnifiedPolicyNumberResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByUnifiedPolicyNumberAsync(int regionId, string unifiedPolicyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault), Action="http://tempuri.org/IPolicyStatusService/GetStatusByNumberDataObjectNotFoundFaultF" +
            "ault", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByNumber(int regionId, string series, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByNumberResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByNumberAsync(int regionId, string series, string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByTemporaryPolicyNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByTemporaryPolicyNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault), Action="http://tempuri.org/IPolicyStatusService/GetStatusByTemporaryPolicyNumberDataObjec" +
            "tNotFoundFaultFault", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByTemporaryPolicyNumber(int regionId, string temporaryPolicyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByTemporaryPolicyNumber", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByTemporaryPolicyNumberResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByTemporaryPolicyNumberAsync(int regionId, string temporaryPolicyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByFIOBirthday", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByFIOBirthdayResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault), Action="http://tempuri.org/IPolicyStatusService/GetStatusByFIOBirthdayDataObjectNotFoundF" +
            "aultFault", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.Policy GetStatusByFIOBirthday(int regionId, string lastname, string firstname, string secondname, System.Nullable<System.DateTime> birthday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetStatusByFIOBirthday", ReplyAction="http://tempuri.org/IPolicyStatusService/GetStatusByFIOBirthdayResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Policy> GetStatusByFIOBirthdayAsync(int regionId, string lastname, string firstname, string secondname, System.Nullable<System.DateTime> birthday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetFIOByPhone", ReplyAction="http://tempuri.org/IPolicyStatusService/GetFIOByPhoneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(OMInsurance.Services.Tests.DMZPolicyStatusService.DataObjectNotFoundFault), Action="http://tempuri.org/IPolicyStatusService/GetFIOByPhoneDataObjectNotFoundFaultFault" +
            "", Name="DataObjectNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/OMInsurance.Services.Entities.Core.Faults" +
            "")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.Person GetFIOByPhone(int regionId, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetFIOByPhone", ReplyAction="http://tempuri.org/IPolicyStatusService/GetFIOByPhoneResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Person> GetFIOByPhoneAsync(int regionId, string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetRegions", ReplyAction="http://tempuri.org/IPolicyStatusService/GetRegionsResponse")]
        OMInsurance.Services.Tests.DMZPolicyStatusService.Region[] GetRegions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPolicyStatusService/GetRegions", ReplyAction="http://tempuri.org/IPolicyStatusService/GetRegionsResponse")]
        System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Region[]> GetRegionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPolicyStatusServiceChannel : OMInsurance.Services.Tests.DMZPolicyStatusService.IPolicyStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolicyStatusServiceClient : System.ServiceModel.ClientBase<OMInsurance.Services.Tests.DMZPolicyStatusService.IPolicyStatusService>, OMInsurance.Services.Tests.DMZPolicyStatusService.IPolicyStatusService {
        
        public PolicyStatusServiceClient() {
        }
        
        public PolicyStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolicyStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolicyStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByUnifiedPolicyNumber(int regionId, string unifiedPolicyNumber) {
            return base.Channel.GetStatusByUnifiedPolicyNumber(regionId, unifiedPolicyNumber);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByUnifiedPolicyNumberAsync(int regionId, string unifiedPolicyNumber) {
            return base.Channel.GetStatusByUnifiedPolicyNumberAsync(regionId, unifiedPolicyNumber);
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByNumber(int regionId, string series, string number) {
            return base.Channel.GetStatusByNumber(regionId, series, number);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByNumberAsync(int regionId, string series, string number) {
            return base.Channel.GetStatusByNumberAsync(regionId, series, number);
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo GetStatusByTemporaryPolicyNumber(int regionId, string temporaryPolicyNumber) {
            return base.Channel.GetStatusByTemporaryPolicyNumber(regionId, temporaryPolicyNumber);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.PolicyInfo> GetStatusByTemporaryPolicyNumberAsync(int regionId, string temporaryPolicyNumber) {
            return base.Channel.GetStatusByTemporaryPolicyNumberAsync(regionId, temporaryPolicyNumber);
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.Policy GetStatusByFIOBirthday(int regionId, string lastname, string firstname, string secondname, System.Nullable<System.DateTime> birthday) {
            return base.Channel.GetStatusByFIOBirthday(regionId, lastname, firstname, secondname, birthday);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Policy> GetStatusByFIOBirthdayAsync(int regionId, string lastname, string firstname, string secondname, System.Nullable<System.DateTime> birthday) {
            return base.Channel.GetStatusByFIOBirthdayAsync(regionId, lastname, firstname, secondname, birthday);
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.Person GetFIOByPhone(int regionId, string Phone) {
            return base.Channel.GetFIOByPhone(regionId, Phone);
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Person> GetFIOByPhoneAsync(int regionId, string Phone) {
            return base.Channel.GetFIOByPhoneAsync(regionId, Phone);
        }
        
        public OMInsurance.Services.Tests.DMZPolicyStatusService.Region[] GetRegions() {
            return base.Channel.GetRegions();
        }
        
        public System.Threading.Tasks.Task<OMInsurance.Services.Tests.DMZPolicyStatusService.Region[]> GetRegionsAsync() {
            return base.Channel.GetRegionsAsync();
        }
    }
}
